package com.smartInvoice.admin_service.domain;

public enum AdminActionType {
	BLOCK_USER,
	UNBLOCK_USER,
	DELETE_USER,
	CANCEL_SUBSCRIPTION,
	CHANGE_PLAN,
	LOG_REFUND,
	ADD_NOTE,
	TRIGGER_PASSWORD_RESET,
	DISMISS_FLAG,
	MARK_TRUSTED,
	RECONCILE_SUBSCRIPTION,
	LOGIN_FAILURE,
	BLOG_CREATED,
	BLOG_UPDATED,
	BLOG_PUBLISHED,
	BLOG_UNPUBLISHED,
	BLOG_ARCHIVED,
	BLOG_RESTORED,
	BLOG_CATEGORY_CREATED,
	BLOG_CATEGORY_UPDATED,
	BLOG_MEDIA_UPLOADED
}
